mdd=['chengdu','xian','hangzhou','shanghai']
print(mdd)
print(sorted(mdd))
print(mdd)
print(sorted(mdd,reverse=True))
print(mdd)
mdd.reverse()
print(mdd)
mdd.reverse()
print(mdd)
mdd.sort()
print(mdd)
mdd.sort()
print(mdd)
print(len(mdd))
for value in range(1,6):
    print=(value)
